const express = require('express')
const router = express.Router()

require('./routers/categories')(router)
require('./routers/servers')(router)
require('./routers/server')(router)
require('./routers/processors')(router)
require('./routers/disks')(router)
require('./routers/filter')(router)
require('./routers/os')(router)
require('./routers/lanPorts')(router)
require('./routers/lanPortsValues')(router)
require('./routers/diskValues')(router)
require('./routers/wp')(router)
require('./routers/cart')(router)
require('./routers/user')(router)
require('./routers/managers')(router)
require('./routers/company')(router)
require('./routers/clients')(router)
require('./routers/hba')(router)
require('./routers/counter')(router)
require('./routers/orderStatus')(router)
require('./routers/raidcontrollers')(router)
require('./routers/transc')(router)
require('./routers/orders')(router)
module.exports = router
